# Generated by Django 3.1.7 on 2021-04-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_total_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_count',
        ),
    ]
