# Generated by Django 3.1.7 on 2021-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='back_image',
            field=models.ImageField(default='default.jpg', upload_to='background_pics'),
        ),
    ]
