# Generated by Django 3.1.7 on 2021-04-03 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0002_poll_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='votedBy',
            field=models.ManyToManyField(related_name='votedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
