# Generated by Django 3.1.7 on 2021-04-03 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0003_poll_votedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='votedBy',
            field=models.ManyToManyField(blank=True, related_name='votedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
