# Generated by Django 3.1.5 on 2021-04-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20210403_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='percentage_o1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='poll',
            name='percentage_o2',
            field=models.FloatField(default=0.0),
        ),
    ]
