# Generated by Django 3.1.7 on 2021-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_poll_image_back_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='image_back_no',
        ),
        migrations.AddField(
            model_name='poll',
            name='image_bg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
