# Generated by Django 3.1.7 on 2021-04-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20210404_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='back_image',
        ),
    ]
