# Generated by Django 3.1.7 on 2021-04-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_remove_poll_back_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option3_count',
        ),
    ]
